all: cases
cases:
	../dreadlock -o case1.als -t case1 test1.dlk
	../dreadlock -o case2.als -t case2 test1.dlk
	../dreadlock -o case3.als -t case3 test1.dlk
	../dreadlock -o case4.als -t case4 test1.dlk
	../dreadlock -o case5.als -t case5 test1.dlk
	../dreadlock -o case6.als -t case6 test1.dlk

clean:
	@rm -f *.als

